name: firebasechatapp
description: A reactive chat application fueled by a Firebase Realtime Database.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  intl: 0.17.0
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  provider: ^6.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
